# Generated by Django 5.1.7 on 2025-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='accidentreport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
