# Generated by Django 5.1.7 on 2025-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_accidentreport_siren_accidentreport_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
