# Generated by Django 5.1.7 on 2025-04-03 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_accidentreport_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentreport',
            name='vic_number',
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_type',
            field=models.CharField(max_length=255),
        ),
    ]
