# Generated by Django 5.1.7 on 2025-04-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_accidentreport_vic_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentreport',
            name='location',
        ),
    ]
