# Generated by Django 5.1.7 on 2025-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_accidentreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du signalement'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='siren',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro SIREN'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Web'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Email de l'arnaqueur"),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu de l'arnaque"),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'arnaqueur"),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spammer Phone Number'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='spam_type',
            field=models.CharField(max_length=255, verbose_name='Type de spam'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='vic_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email de la victime'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de votes'),
        ),
    ]
